### ISSUE TITLE
PUT & POST Method mismatch ?

### ISSUE THREAD

**Issue by clawfire** [alassek/jquery.rest#10]
According to [this article](http://developer.mindtouch.com/REST/REST_for_the_Rest_of_Us) didn't you misunderstood difference between PUT and POST ? Just ask ;)

**Comment by alassek** [comment]
Nope, [Rails uses POST for create and PUT for update](http://guides.rubyonrails.org/routing.html#crud-verbs-and-actions). It should probably use PATCH instead, but jQuery.rest was built to work with what is, not what should be.

I might make the verb-mapping configurable; that would probably make this more useful for other APIs.

**Comment by clawfire** [comment]
that would be very nice :)

But just to understand, is there's no common agreed standard how rest api should work and wich verb use to do stuff ?

**Comment by alassek** [comment]
There's a 'correct' way to do it according to the original whitepapers, but the the reality of REST is still catching up.

[Steve Klabnik](http://blog.steveklabnik.com/posts/2011-07-03-nobody-understands-rest-or-http) talks a lot about this sort of stuff if you're interested.

**Comment by clawfire** [comment]
thx for the link ;)
