### ISSUE TITLE
$.update does not send right Accept header

### ISSUE THREAD

**Issue by radeno** [alassek/jquery.rest#14]
Hi,

i like principle of REST queries for jQuery, that is really great idea. But i don't know where is problem.

I write simple ordering with acts_as_list, jQuery sortable and jQuery.REST.

Have this action in categories controller:

```
  def update_position
    params[:category].each.with_index do |id, index|
      Category.update_all({position: index+1}, {id: id})
    end

    index
  end
```

After update i want to update positions in HTML table. so have this view:
update_position.js.erb

```
<%- @categories.each do |category| %>
  $('#' + '<%= dom_id(category) %>' + ' .position').html(<%= category.position %>);
<%- end %>
```

But when is JS event called with

```
$.update(
  $(this).data('update-url') + '.js', $(this).sortable('serialize')
);
```

it is returned like JSON (Accept header is application/json at first, second is text/javascript what i want), so my view isn't executed. But when i call event with normal post query:

```
$.post(
  $(this).data('update-url') + '.js', $(this).sortable('serialize');
);
```

it is executed.

**Comment by alassek** [comment]
Try specifying the `contentType` for the request. Does that make a difference?

``` javascript
$.update({
  url: $(this).data('update-url') + '.js',
  data: $(this).sortable('serialize'),
  contentType: 'text/javascript'
})
```

**Comment by radeno** [comment]
There are some weird behaviors.

for first, that must be (works correct) takes from jQuery docs.
`dataType: 'script'`

contentType is default application/x-www-form-urlencoded

And there is problem that i missed dataType. On documentation is written `Default: Intelligent Guess (xml, json, script, or html)` guess failed :)

For second. There are some inconsistency:
this shorthand:

```
      $.update({
        url: $(this).data('update-url') + '.js',
        data: $(this).sortable('serialize')
      })
```

send `Accept  application/json, text/javascript, */*; q=0.01` what is wrong
returned header `Content-Type text/javascript; charset=utf-8` is right, but returned JS doesn't work

but full 

```
$.ajax({
        type: 'PUT',
        url: $(this).data('update-url') + '.js',
        data: $(this).sortable('serialize')
      })
```

send `Accept  */*` what is neutral
returns `Content-Type text/javascript; charset=utf-8` is right, returned JS works

And right sender and returned have this syntax, or shorthand:

```
$.ajax({
        type: 'PUT',
        url: $(this).data('update-url') + '.js',
        data: $(this).sortable('serialize'),
        dataType: 'script'
      })
```

sends`Accept  text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01` what is right
returns `Content-Type text/javascript; charset=utf-8` what is right and JS works.

But main question is:

When REST URI defines accept header by URI suffix (.js, .xml, .html, .json), why is necessary to define accept header additionally with dataType directive.
I know that major URI do not respect suffix and sends accept header. But when i search it that is doesn't sends right, i get headache little bit :)

Some discussion about accept: http://stackoverflow.com/questions/381568/rest-content-type-should-it-be-based-on-extension-or-accept-header

Or maybe i completely misunderstood REST :)
