### ISSUE TITLE
Use real PUT and DELETE requests for browsers that support them

### ISSUE THREAD

**Issue by alassek** [alassek/jquery.rest#5]
IE < 9 don't support `PUT` or `DELETE` so we still need to tunnel requests for those browsers.

Double-check browser support for `PUT` and `DELETE` in standards-compliant browsers.

**Comment by EnigmaCurry** [comment]
IE does support PUT and DELETE in the context of an XmlHTTPRequest, you just can't set those methods on a HTML form tag.

$.ajax({url:"/",type:"DELETE"})
$.ajax({url:"/",type:"PUT"})

Both work in IE7 at least, I'm not sure how far back it goes.. maybe 6 too?

**Comment by alassek** [comment]
After doing some more research on this it looks like I was confusing the HTML FORM spec with the XmlHttpRequest spec.

From what I'm reading, while IE does support PUT and DELETE in the xhr, a 302 Redirect will break the behavior and make it use GET. I'm not sure how serious a problem that is. It would probably still be acceptable to use them by default and allow falling back to tunneling if required.
